pl.um <- c("augitite","chromitite","clinopyroxenite","dunite","glimerite","hazburgite","lherzolite","orthopyroxenite","peridotite","wehrlite","websterite")
pl.mf <- c("anorthosite","diabase","dolerite","gabbro","lamprophyre","monzogabbro","nepheline-gabbro","norite","shonkinite","troctolite")
pl.in <- c("diorite","enderbite","monzodiorite","monzonite","monzosyenite","sanukitoid","tonalite")
pl.fs <- c("adamellite","alkali granite","aplite","charnockite","granite","granodiorite","granofels","granophyre","monzogranite","syenite","syenogranite","trondhjemite")
pl.ex <- c("essexite","fenite","foidite","leucitite","minette","nephelinite","phoscorite","tachylyte")
vo.um <- c("boninite","komatiite","picrite")
vo.mf <- c("absarokite","alaskite","alkali basalt","ankaramite","basalt","basaltic andesite","basanite","hawaiite","icelandite","kimberlite","lamproite","nepheline-basalt","sanukite","shosonite","tholeiite")
vo.in <- c("adakite","andesite","benmoreite","mugearite","pantellerite","trachyandesite","trachybasalt","trachydolerite")
vo.fs <- c("dacite","domite","ignimbrite","leucophyre","phonolite","pumice","rhyodacite","rhyolite","trachydacite","trachyte")
vo.ex <- c("carbonatite","hauynophyre","latite","pyroclastic-fall","pyroclastic-flow","sanidinite","tephrite","theralite","tuff","scoria","volcaniclastic")
cl.me <- c("amphibolite","augengneiss","blueschist","buchite","calcsilicate","calc-silicate","eclogite","garnetite","gneiss","granophyre","granulite","greenschist","greenstone","hornblendite","hornfels","iron formation","ironstone","jadeitite","magnetite","marble","meta-adamellite","meta-andesite","meta-anorthosite","meta-aplite","meta-arenite","meta-argilite","meta-arkose","meta-basalt","meta-basite","meta-breccia","meta-carbonatite","meta-chert","meta-chert","meta-claystone","meta-diorite","meta-dolerite","meta-dunite","meta-exhalite","meta-felsite","meta-gabbro","meta-granite","meta-granodiorite","meta-greywacke","meta-hornblendite","meta-igneous","meta-keratophyre","meta-latite","meta-mafite","meta-monzodiorite","meta-monzonite","meta-norite","meta-pegmatite","metapelite","meta-pelite","meta-peridotite","meta-porphyry","meta-pyroxenite","meta-quartzite","meta-rhyodacite","meta-rhyolite","meta-sandstone","meta-sediment","meta-syenite","meta-shale","meta-spilite","meta-tactite","meta-tonalite","meta-trachyte","meta-trondhjemite","meta-tuff","metavolcanic","meta-volcaniclastic","migmatite","mylonite","novaculite","orthogneiss","paragneiss","phyllite","pyrite","pyroxenite","quartzite","rodingite","schist","serpentinite","skarn","slate","soapstone","taconite","tactite","talc","tourmalinite")
cl.al <- c("albitite","arenite","calcrete","greisen","magnesite")
cl.ve <- c("pegmatite","quartz vein")
cl.or <- c("magnetite","massive sulfide","oil shale","opal","pegmatite","placer","porphyry-stockwork","pyrite","sulfate deposit")
cl.sd <- c("agglomerate","allivalite","alluvium","anhydrite","arenite","argilite","argilitic","arkose","biogenic","black-shale","breccia","calcarenite","calcite","calcrete","carbonate","chemical sediments","chert","chert-jasperoid","clastic","clay","claystone","coal","concretion","conglomerate","diatomite","dolomite","epigenetic","evaporite","exhalite","flysch","glauconite","gravel","gravel and sand","greywacke","gypsum","limestone","marl","marlstone","mud","mudstone","oil shale","pelite","phosphate","phosphorite","placer","quartz arenite","sand","sandstone","siliceous","siliciclastic","silt","siltstone","till","travertine","turbidite")
cl.xe <- c("harzburgite","lherzolite","peridotite","pyroxenite")
pluto <- list(ultramafic=pl.um,mafic=pl.mf,intermediate=pl.in,felsic=pl.fs,exotic=pl.ex)
volca <- list(ultramafic=vo.um,mafic=vo.mf,intermediate=vo.in,felsic=vo.fs,exotic=vo.ex)
iglist <- list(plutonic=pluto,volcanic=volca)
rock.class <- list(not_defined="",alteration=cl.al,igneous=iglist,metamorphic=cl.me,ore=cl.or,sedimentary=cl.sd,vein=cl.ve,xenolith=cl.xe)
#print(rock.class)


